replicaCount: 1

image:
  tag: "0.0.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: "256M"
    cpu: ".25"

env:
  publicSearchApi: "http://search:8080"
  publicMongoApi: "http://api:8080/v2"
  gTag: "" # leave empty for dev
  